tasks:
    - name: Install dependencies
      command: |
        npm install
    - name: Generate service account
      command: |
        eval $(gp env -e)
        echo "$LANGAME_SVC_PROD" > ./svc.prod.json
        echo "$LANGAME_SVC_DEV" > ./svc.dev.json
    - name: Auth gcloud
      command: |
        gcloud auth login --no-launch-browser
        gcloud projects list
        echo "gcloud config set project [PROJECT_ID]"
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - aaron-bond.better-comments
    - GitHub.copilot
    - gitpod.gitpod-desktop
    - googlecloudtools.cloudcode
    - hbenl.vscode-test-explorer
    - k--kato.intellij-idea-keybindings
    - mechatroner.rainbow-csv
    - ms-azuretools.vscode-docker
    - ms-kubernetes-tools.vscode-kubernetes-tools
    - ms-python.vscode-pylance
    - ms-toolsai.jupyter
    - mushan.vscode-paste-image
    - Perkovec.emoji
    - RandomFractalsInc.vscode-data-preview
    - redhat.vscode-yaml
    - stylelint.vscode-stylelint
    - toba.vsfire
    - wix.vscode-import-cost
    - zxh404.vscode-proto3
    - 42crunch.vscode-openapi