name: Run Continuous Integration & Continuous Delivery Prod
on:
  push:
    tags:
      - "v*.*.*"
env:
  REACT_APP_ENVIRONMENT: production
jobs:
  ci_cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm i && npm run build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:prod-website --message \"${{ github.event.head_commit.message }}\" --project langame-86ac4
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_PROD }}
          PROJECT_ID: langame-86ac4
      - name: Generate Changelog
        run: git log | head > ${{ github.workspace }}-CHANGELOG.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.txt
        env:
          GITHUB_REPOSITORY: langa-me/langame-website
      - name: Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: '🤖 The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed to https://langa.me 🤖. Commit: ${{ github.event.head_commit.message }}' 